### PR TITLE
optimized Makefile structure and improved install/uninstall

### PR DESCRIPTION
**Pull request by benjamin-weiss**
As proposed by @rchurchley in #82 I also removed the contributors
script. The corresponding changes in the mtheme.dtx are already
implemented in #83.

The additional make rules are already described in the documentation
(also #83)

### CODE REVIEW

**Comment by benjamin-weiss** [comment]
Should be a safe uninstall now.

@matze By the way, do you still want to keep the docker build rules for a little bit? Or shall I remove them right now within this PR?

**Comment by matze** [comment]
I will redirect that question to @awalterschulze. I personally don't use Docker but if there is a large user base that benefits from this, I'd keep it.

**Comment by awalterschulze** [comment]
I am a user :)
It is quite nice to be able to git clone and then start editing the example file and just run make docker-run to get a pdf.
Maybe its just me, but in the worst case these are very nice and testable installation instructions.

On a side note: The Dockerfile is in the contrib folder, but it should be in the root folder.

**Comment by rchurchley** [comment]
As far as I can see, the main purpose of the Dockerfile is to allow some users an easy way of installing the Fira fonts. I think it can and probably should stay until we can move to a different solution for font installation (see #85)

**Comment by awalterschulze** [comment]
Basically yes, but also its a nice way to test the font installation.

**Comment by benjamin-weiss** [comment]
> I think it can and probably should stay until we can move to a different solution for font installation (see #85).

Ok, so let's keep it for now.

**Comment by benjamin-weiss** [comment]
As it seems we decided to keep the docker build rules, I think this one can also be merged.

**Comment by matze** [comment]
Alright, thanks!

**Pull request merged**
