### PR TITLE
add missing font features

### PR DESCRIPTION
**Pull request by ronnychevalier**
Italic and BoldItalic font were missing

### CODE REVIEW

**Comment by matze** [comment]
The italic variants are chosen automatically. For italic you specified the normal Fira Sans variant which is bolder than the light one and now looks out-of-place.

**Comment by ronnychevalier** [comment]
On Tue, May 5, 2015 at 7:59 AM, Matthias Vogelgesang
<notifications@github.com> wrote:
>
> The italic variants are chosen automatically. For italic you specified the normal Fira Sans variant which is bolder than the
> light one and now looks out-of-place.

Ah yes it should have been a light one.

But for me it is not chosen automatically I need to specify the italitc font.

**Comment by matze** [comment]
> But for me it is not chosen automatically I need to specify the italitc font.

Could you update this pull request with the light italic variant?

**Comment by ronnychevalier** [comment]
On Tue, May 5, 2015 at 2:23 PM, Matthias Vogelgesang
<notifications@github.com> wrote:
>
> But for me it is not chosen automatically I need to specify the italitc font.
>
> Could you update this pull request with the light italic variant?
>

I updated the pull request a couple of weeks ago, but forgot to tell you :)

**Comment by matze** [comment]
Ah sorry, I think that's in part GitHub's fault to not notify the owner of a repository if some PR changed.

**Pull request merged**
