### PR TITLE
fixes #152 – fixes conditional font loading for LuaTeX

### LINKED ISSUE #152: Cannot find fira fonts
The change to conditional font detection has broken metropolis for my installation. I am on ubuntu 14.04 with TexLive 2015 and have fira v4.1 installed. When compiling with lualatex, I receive a warning that the fira fonts cannot be found and they are not used in the resulting pdf. It worked fine with the previous font methods.

### PR DESCRIPTION
**Pull request by benjamin-weiss**

### CODE REVIEW

**Comment by matze** [comment]
Did this change really affect the output of the PDF?

**Comment by benjamin-weiss** [comment]
Sure, as we append the code to the documentation, every piece of code we change changes the output of it.

**Comment by matze** [comment]
Yes, of course. But I meant if this had a real effect on the visual outcome which I doubt. Unfortunately, Git is not very good at version controlling binary data and I really want to avoid growing the repo unnecessarily. As of now, a fresh clone already wastes several MB of bandwidth for some TeX files and two (rather smallish) PDFs. But I'll let that slip :-)

**Comment by benjamin-weiss** [comment]
Ok, now I understand what you mean. Maybe we should just exclude the PDFs from the repository once the CTAN release is finished and just link to the PDFs hosted by CTAN.

**Pull request merged**
