### PR TITLE
Addresses issue with TeX capacity exceeded

### LINKED ISSUE #20: "TeX capacity exceeded" when using allowframebreaks
This MWE:

````
\documentclass[titleprogressbar]{beamer}
\usetheme{m}
\usepackage{lipsum}
\begin{document}

\begin{frame}[allowframebreaks]
\frametitle{A Frame Title}
\lipsum
\end{frame}

\end{document}
````

bombs with 

````
...
Runaway argument?
! TeX capacity exceeded, sorry [main memory size=5000000].
\reserved@a #1#2->\let #2#1\reserved@a 
                                       
l.9 \end{frame}
...
````

### PR DESCRIPTION
**Pull request by elliottd**
\begin{frame}[allowframebreaks] needs the title to be protected when
autobreaking because that is fragile.

There may be some [side-effects](http://texblog.net/help/latex/fragile.html)
when applying \protect to the title if used in combination with length and
counter commands.

Fixes #20

### CODE REVIEW

**Comment by rchurchley** [comment]
This pull request fixes #20, but protecting `\insertframetitle` also prevents it from being affected by `\MakeLowercase`. I think this is probably inevitable — the crash seems to result from the interaction between `allowframebreaks` and `\MakeLowercase`. It may be less confusing to instead remove `\MakeLowercase` or ask the user to invoke it themselves. This solution is suggested as pull request #58.

**Comment by matze** [comment]
Does this mean this PR is then obsolete?

**Comment by elliottd** [comment]
I'll defer to @rchurchley about the true underlying cause of the problem here.

However, you may want to pull in the references frames in `demo.tex` and the references in `demo.bib` that demonstrate that allowframebreaks actually works.

**Comment by matze** [comment]
Do you want to create a new commit for proper attribution?

**Comment by rchurchley** [comment]
Looks like this can be merged now and #20 closed?

**Comment by matze** [comment]
It must be rebased against master.

**Pull request closed without merging**
