### PR TITLE
Add bg color to alerted and example blocks.

### PR DESCRIPTION
**Pull request by jdahm**
Addresses #38. Please test.

### CODE REVIEW

**Comment by matze** [comment]
Something's off with the height of both the block title and the block itself.

**Comment by jdahm** [comment]
@chraibi Thanks for testing. Just had a chance to put together a test myself and incorporated your changes. I've cleaned up the syntax a bit and increased the contrast between the block title and body backgrounds, which is a bit lacking in your example. Adding the commit now.

If you would like to revert to what you had, just add in the preamble
```tex
\usetheme[blockbg]{m}
\useinnertheme{rectangles}

\makeatletter
\setbeamercolor{block title}{use=palette primary,parent=palette primary,bg=palette primary.bg!80!fg}                             
\setbeamercolor{block title alerted}{use=alerted text,parent=palette primary,fg=alerted text.fg, bg=alerted text.bg!75!fg}       
\setbeamercolor{block title example}{use=example text,parent=palette primary,fg=example text.fg,bg=example text.bg!75!fg}        

\setbeamercolor{block body}{parent=normal text,use=block title,bg=block title.bg!80}                                             
\setbeamercolor{block body alerted}{parent=normal text,use=block title alerted,bg=block title alerted.bg,bg=alerted              
text.bg!80!fg}                                                                                                                   
\setbeamercolor{block body example}{parent=normal text,use=block title example,bg=block title example.bg,bg=example              
text.bg!80!fg}       
\makeatother
```

@matze I noticed that when I used this theme as well (now trying to transition to reveal.js, but that's unrelated here). The cause is that beamer seems to be defaulting to something like the `rectangles` inner theme. This is either since mtheme sets this (which it doesn't) or this is a beamer default. If you instead use something like `\useinnertheme{rounded}` the spacing is much better. It would be nice if someone added better looking default spacing settings to mtheme itself.

**Comment by matze** [comment]
@jdahm: so it's ready for merge?

**Comment by jdahm** [comment]
Yes, it is. Not quite the colors shown above (I made the background lighter) but we'll never find a setting that pleases everyone. It can always be customized.

**Comment by chraibi** [comment]
@jdahm yes that looks better. Thanks! 
Apropos your remark concerning ```\useinnertheme{rounded}``` that makes the spacing much better indeed. Only the master slide gets totally changed, which is not nice.

**Pull request merged**
