### PR TITLE
upper part of logo redrawn by hand to get proper transparency

### PR DESCRIPTION
**Pull request by benjamin-weiss**
I have redrawn your "vectorized chaos" :smirk: in the top part of the logo to get a proper transparency. I hope it still looks like you intended.

Kind of strange is the size of the `eps` and `pdf` that Illustrator produces: `svg` → 8 KB `eps` → 986 KB

Another thing: It would be nice if we could set the logo color directly in LaTeX. Any idea whats the best way to do that?

### CODE REVIEW

**Comment by rchurchley** [comment]
Opening that `svg` in Inkscape and saving it as an `eps` results in a 21kB file. I think the `svg` filesize can be reduced as well if you put it through [`svgo`](https://github.com/svg/svgo).

**Comment by benjamin-weiss** [comment]
Thanks for the info. I thought about trying to convert it with inkscape. But I was too lazy to install it. :smirk:

**Comment by rchurchley** [comment]
> It would be nice if we could set the logo color directly in LaTeX. Any idea whats the best way to do that?

It turns out that TikZ includes an operation to draws a path specified in the SVG path data syntax. The TikZ manual gives an example:
```latex
\begin{tikzpicture}
  \filldraw [fill=red!20] (0,1) svg[scale=2] {h 10 v 10 h -10}
    node [above left] {upper left} -- cycle;
  \draw svg {M 0 0 L 20 20 h 10 a 10 10 0 0 0 -20 0};
\end{tikzpicture}
```
Using this, it should not be too difficult to express the paths in `logo/logo-redrawn.svg` to TikZ, allowing us to automatically take colours from the theme.

**Comment by matze** [comment]
@benjamin-weiss: you can just overwrite the original file(s). I just wanted to get #95 get going :smile:

Concerning re-doing the logo, I am sceptical because than we cannot re-use it easily for other purposes. But if we decide, to just keep it within the theme itself, why not.

**Comment by benjamin-weiss** [comment]
> you can just overwrite the original file(s)

I will do that. Just wanted to solve the file size issue first.

> It turns out that TikZ includes an operation to draws a path specified in the SVG path data syntax.

Nice. It seems there is even an [export extension for inkscape](https://github.com/kjellmf/svg2tikz).

**Comment by rchurchley** [comment]
I think it's fine to go with just the `svg`-`eps`-`pdf` options — I don't expect the logo to show up anywhere but the demo slides, so it doesn't necessarily need to change colour. Just thought I'd mention that taking colours from the scheme was possible :)

I would like to cut down on the file sizes before merging this, however. Can you re-export with Inkscape, @benjamin-weiss, or would you prefer one of us to do it?

**Comment by benjamin-weiss** [comment]
> Can you re-export with Inkscape, @benjamin-weiss, or would you prefer one of us to do it?

I will do it. Even though we probably not use it. I'm curios about the TikZ exporter. So I will eventually install inkscape after all.

**Comment by rchurchley** [comment]
I finally realized that this pull request was updated eight months ago with much better file sizes! Thanks for doing that, and sorry it took us so long to notice.

I'm still not sure we need to keep around all 995kB of the full Illustrator-generated file. If edibility is a concern, then we can keep around a second Inkscape-generated file where the text is not converted to paths (roughly 16kB).

Apart from that, I think this is a good tweak!

**Comment by benjamin-weiss** [comment]
I rebased this PR. Do we want to keep a version where the text is not converted to paths? I removed it for the time being, but still have it (as a small version saved with inkscape).

**Comment by rchurchley** [comment]
Perfect. Looks like we can merge now!

I don't think we need to keep the non-converted version as a separate file in the repo. However, you could add that version and then revert it — that will keep the demo directory clean while ensuring we still have the text-editable file still available in the commit history.

**Pull request merged**
